### ISSUE TITLE
Maintaining/Updating

### ISSUE THREAD

**Issue by LanguageStuff** [seth-js/yomichan-de#1]
You seem to be doing as many languages as possible, which is great.  But do you ever plan on updating the wordlists or adding new features for each dict or do you mainly plan on just a one-and-done strategy?

**Comment by seth-js** [comment]
I'm done for now with Yomichan. I accomplished what I originally planned to create which was a nice hover dictionary option for Russian, Spanish, French, and some other languages that were requested.

I'm also ironically no longer using it. I ask ChatGPT to break down sentences when I'm looking things up while reading Spanish or Mandarin.
