### ISSUE TITLE
Asking for help

### ISSUE THREAD

**Issue by Pakamer** [seth-js/yomichan-de#2]
Hello! Recently I’ve started learning German, and I came across the Yomichan project; then I found your version of Yomichan. I’m having some difficulties making it work and was wondering if you could help me. I’ve downloaded the repository, and followed first few steps, but: 1) I can’t find the “yomichan-settings-2022-11-18.json” file, nor can I find 2) the “German Dictionary.zip” file. Am I missing something? (probably yes...) Sorry for the inconvenience.

Best regards,
Aleks

**Comment by seth-js** [comment]
No problem. It's on the [Releases](https://github.com/seth-js/yomichan-de/releases) page.

**Comment by Pakamer** [comment]
Thank you very much! Everything seems to be working, except the integration with Anki. When I click the plus sign to add a word into Anki, the following message appears: “2 errors occurred:
    • Template render error for {expression}
    • Template render error for {glossary}”. 
Also in the yomichan settings in the “Anki Card Templates” section a red message reads “null has no properties”
Do you know how to fix that?

**Comment by seth-js** [comment]
What browser are you using? I can try setting everything up and seeing if I get the error.

**Comment by seth-js** [comment]
The repository has been updated. Delete the dictionary, remove the extension, delete the repository you downloaded, and then follow the new instructions. Let me know if you still have issues.

**Comment by Pakamer** [comment]
It's working! Thank you so so much!!! (Of course shout-out to all the people who have worked on the yomichan project). Is there any way to thank you “materially”, for example by paypaling you a symbolic amount of money?
