### ISSUE TITLE
Plans for other languages with Yomichan

### ISSUE THREAD

**Issue by Jovnik** [seth-js/yomichan-de#3]
Hey Seth,

Thanks so much for creating these modified Yomichan extensions for other languages, they have been beyond helpful and I hope that more people in the language learning community get to find them.
I was just wondering if you have any plans for creating extensions for other languages? Or if there is some way we could create support for other languages ourselves? 

Cheers!

**Comment by seth-js** [comment]
Thanks for the kind words.

>any plans for creating extensions for other languages

Not right now, but if a language is requested, and it seems simple enough like Swedish or Italian, then I might consider adding another one at some point.

>some way we could create support for other languages ourselves

I explained some of the process in [this issue](https://github.com/seth-js/yomichan-sr-hr/issues/5).

You can look at the `src` folder in my `yomichan-de` and `yomichan-es` repositories to see how the dictionary is created. The extension itself should already work with most other European languages without any other edits.

I'm a bit busy right now, but I've moved the yomichan codebase over to yomitan now that it has a stable release. Some bugs have been fixed, and I changed the dictionary generation process a bit for some languages. I'm still testing everything.

**Comment by Jovnik** [comment]
That's fair enough! Just out of curiosity are you learning the languages for which you made the other yomichan versions for? I'm looking at starting to learn Italian so I'll dive in and see if I can get the Italian dictionary going for the extension. Cheers for pointing me in the right direction. Happy new year!

**Comment by seth-js** [comment]
>are you learning the languages for which you made the other yomichan versions for

I've dabbled with all of them, but I'm focused on Spanish right now.

Happy new year to you too.
