### ISSUE TITLE
Popup on compound words

### ISSUE THREAD

**Issue by migraine-user** [seth-js/yomichan-de#5]
If you try to look up on the word "Polizeistelle" by hovering over the P, there is no pop-up. 

I think it should try to look up the word "Polizei" when I do that. 

I believe it always tries to match the entire substring starting from the cursor position(i.e Polizeistelle when cursor is on P), but I think it should show the longest word that matches with a dictionary entry.

**Comment by seth-js** [comment]
I recommend you move over to [Yomitan](https://yomitan.wiki/).

1. Install the addon. A welcome page will pop up.
2. Turn on `Enable recommended permissions` and `Enable optional permissions`.
3. Set the `Language` to German.
4. Select the option `Get recommended dictionaries…`.
5. Select `Download` for `kty-de-en`.
6. After that's done, select `Configure Installed and enabled dictionaries…`, and import this [IPA](https://github.com/yomidevs/kaikki-to-yomitan/releases/latest/download/kty-de-en-ipa.zip) dictionary.
7. Turn `Show this welcome guide on browser startup` off.
8. Select `More customization options are available on the Settings page`.
9. At the bottom left of the `Yomitan Settings` page, turn `Advanced` on.
10. Select the `Translation` section.
11. Set `Dictionary search resolution` to `Letter`
12. Select the `Scanning` section.
13. Set `Scan resolution` to `Character`.

With all this, you'll have a much more up-to-date German dictionary with more advanced features and support. Audio support is already built-in, and there's no need to side-load the addon each time you want to use it.

Hovering over `Polizeistelle` will show `Polizei`. If you hover over the `s`, the entry for `Stelle` should also appear.
